#! /bin/bash

source ~/.config/batterylifenotify/config.cfg # don't put anything malicious in there 😠

status=`cat $BATTERY_DIR/status`
capacity=`cat $BATTERY_DIR/capacity`

if [ "$status" = Discharging -a "$capacity" -le $MIN ]; then
	if ! [ -f $BELOWFILE ]; then
		echo $LOW_BATTERY_MESSAGE | xargs notify-send -i battery
		touch $BELOWFILE
		rm $ABOVEFILE 2>/dev/null
	fi
elif [ "$status" = "Charging" -a "$capacity" -ge $MAX ]; then
	if ! [ -f $ABOVEFILE ]; then
		echo $HIGH_BATTERY_MESSAGE | xargs notify-send -i battery
		rm $BELOWFILE 2>/dev/null
		touch $ABOVEFILE
	fi
else
	rm $BELOWFILE $ABOVEFILE 2>/dev/null
fi

