#! /bin/bash
BELOWFILE=/tmp/batblo
ABOVEFILE=/tmp/batabo
MIN=40
MAX=80
BATTERY_DIR=/sys/class/power_supply/BAT0

status=`cat $BATTERY_DIR/status`
capacity=`cat $BATTERY_DIR/capacity`

if [ "$status" = Discharging -a "$capacity" -le $MIN ]; then
	if ! [ -f $BELOWFILE ]; then
		notify-send -i battery "Battery at $MIN%" "Do you want to plug it in?"
		touch $BELOWFILE
		rm $ABOVEFILE 2>/dev/null
	fi
elif [ "$status" = "Charging" -a "$capacity" -ge $MAX ]; then
	if ! [ -f $ABOVEFILE ]; then
		notify-send -i battery "Battery at $MAX%" "Do you want to unplug it?"
		rm $BELOWFILE 2>/dev/null
		touch $ABOVEFILE
	fi
else
	rm $BELOWFILE $ABOVEFILE 2>/dev/null
fi

